from __future__ import annotations

import re

# Slovenian UI / assessment wording. Research titles and source names remain in
# their original English where that is clearer for scientific traceability.
SL_TEXT = {
    # General / workflow
    "1 · Client details": "1 · Podatki o stranki / zaposlenem",
    "These details identify the person being assessed and are shared by the first and second assessment.": "Ti podatki identificirajo ocenjevano osebo in se uporabljajo pri prvi in drugi oceni.",
    "Client name or code": "Ime ali koda stranke",
    "Company": "Podjetje",
    "Department / area": "Oddelek / območje",
    "Job title": "Delovno mesto",
    "2 · Assessment": "2 · Ocena",
    "Choose assessment": "Izberi oceno",
    "1st Assessment": "1. ocena",
    "2nd Assessment / Reassessment": "2. ocena / ponovna ocena",
    "Connection with the 1st assessment": "Povezava s 1. oceno",
    "Select the 1st assessment": "Izberi 1. oceno",
    "The 1st assessment was loaded automatically. The final section will compare it with the reassessment.": "Prva ocena je bila samodejno naložena. V zaključnem delu bo primerjana s ponovno oceno.",
    "No 1st assessment was found for this client code.": "Za to kodo stranke ni bila najdena prva ocena.",
    "Enter the client name/code above first.": "Najprej vnesi ime ali kodo stranke.",
    "1st assessment JSON": "JSON prve ocene",
    "The file could not be read as a valid ErgoFit assessment.": "Datoteke ni bilo mogoče prebrati kot veljavne ocene ErgoFit.",
    "Interventions implemented between the two assessments": "Ukrepi, izvedeni med prvo in drugo oceno",
    "e.g. chair adjustment, monitor repositioning, task changes, active breaks...": "npr. nastavitev stola, sprememba položaja zaslona, spremembe nalog, aktivni odmori ...",
    "Complete all sections below for this assessment.": "Izpolni vse spodnje razdelke za to oceno.",
    "Unidentified worker": "Neidentificiran zaposleni",
    "Stage": "Faza",
    "Date": "Datum",
    "ASSESSMENT SUMMARY": "POVZETEK OCENE",
    "Overall picture": "Skupna slika",
    "Not assessed": "Ni ocenjeno",
    "High-priority issues": "Težave visoke prioritete",
    "Issues needing attention": "Težave, ki zahtevajo pozornost",
    "Symptomatic regions": "Območja s simptomi",
    "Save assessment": "Shrani oceno",
    "Save to Google Sheets": "Shrani v Google Sheets",
    "Backup / export": "Varnostna kopija / izvoz",
    "I confirm that I am authorised to store these assessment data.": "Potrjujem, da sem pooblaščen/-a za shranjevanje teh podatkov ocene.",
    "The Google Sheet and Apps Script bridge are ready. Add the Web App URL and token to Streamlit Secrets to activate automatic saving.": "Google Sheet in povezava Apps Script sta pripravljena. Za samodejno shranjevanje dodaj URL spletne aplikacije in žeton v Streamlit Secrets.",

    "Google Sheets automatic connection is not active in the deployed app yet. Until it is activated, the 1st assessment can be loaded from its JSON backup.": "Samodejna povezava z Google Sheets v objavljeni aplikaciji še ni aktivna. Do aktivacije lahko prvo oceno naložiš iz varnostne kopije JSON.",
    "Greek version: terminology and criteria follow ELINYAE office/DSE guidance. English version follows OSHA Computer Workstations guidance.": "Slovenska različica uporablja terminologijo, usklajeno z evropskimi ergonomskimi načeli za delo z zasloni in standardi EN/ISO; lokalne zakonske zahteve je treba preveriti ločeno.",
    "0 = not measured. OSHA uses 90–120° as a neutral reference.": "0 = ni izmerjeno. Kot 90–120° se uporablja kot orientacijska nevtralna referenca, ne kot univerzalni klinični prag.",
    "The visual worksheet shown below is the TuMeke rendition based on ROSA.": "Spodnji vizualni obrazec je prikaz ROSA po različici TuMeke.",
    "Upload the initial assessment JSON in the Worker tab to generate the before/after comparison.": "Za primerjavo pred/po naloži JSON prve ocene v razdelku zaposlenega.",
    "Working posture changes regularly; prolonged static sitting is avoided.": "Delovna drža se redno spreminja; dolgotrajnemu statičnemu sedenju se izogiba.",
    "The back is supported and the trunk is not held for prolonged periods in a markedly bent or twisted posture.": "Hrbet je podprt in trup ni dalj časa v izrazito upognjenem ali zasukanem položaju.",
    "Shoulders are relaxed and not elevated.": "Ramena so sproščena in niso dvignjena.",
    "Elbows remain close to the body.": "Komolci ostajajo blizu telesa.",
    "During keyboard use, elbows are about 90–120°.": "Med uporabo tipkovnice so komolci približno v območju 90–120°.",
    "Wrists and hands remain straight and in-line with the forearms.": "Zapestja in roke ostajajo v nevtralnem položaju ter poravnani s podlaktmi.",
    "Forearms are adequately supported without elevating the shoulders.": "Podlakti so ustrezno podprte brez dvigovanja ramen.",
    "Feet are fully supported on the floor or on a stable footrest.": "Stopala so v celoti podprta na tleh ali na stabilni opori za noge.",
    "There is adequate clearance for the thighs, knees, legs and feet.": "Na voljo je dovolj prostora za stegna, kolena, goleni in stopala.",

    # Symptom history / functional impact
    "<1 week": "<1 teden",
    "1–6 weeks": "1–6 tednov",
    "6–12 weeks": "6–12 tednov",
    ">12 weeks": ">12 tednov",
    "Occasional": "Občasno",
    "Occasionally": "Občasno",
    "1–2 days/week": "1–2 dni/teden",
    "3–5 days/week": "3–5 dni/teden",
    "Daily / almost daily": "Vsak dan / skoraj vsak dan",
    "Symptoms by body region": "Simptomi po telesnih predelih",
    "Record intensity and work interference separately for each selected region.": "Za vsak izbrani predel posebej zabeleži intenzivnost in vpliv na delo.",
    "How long has this problem been present?": "Kako dolgo je ta težava prisotna?",
    "— Not recorded —": "— Ni zabeleženo —",
    "How often is it present?": "Kako pogosto je prisotna?",
    "Previous similar episode?": "Ali je bila podobna epizoda že prej?",
    "Does it interfere with work?": "Ali vpliva na delo?",
    "Do you change pace/task/posture because of it?": "Ali zaradi simptoma spreminjaš tempo, nalogo ali držo?",
    "Work absence due to this symptom in the last 4 weeks (days)": "Odsotnost z dela zaradi tega simptoma v zadnjih 4 tednih (dni)",
    "These fields describe the symptom history and functional impact. They are not converted into a personal disease-probability score.": "Ta polja opisujejo potek simptoma in njegov funkcionalni vpliv. Ne pretvarjajo se v osebno verjetnost bolezni.",
    "Digital eye strain / visual fatigue": "Digitalna obremenitev oči / vidna utrujenost",
    "Musculoskeletal profile & proposed action": "Mišično-skeletni profil in predlagani ukrep",
    "The proposed action combines reported symptoms, functional/work impact and relevant ergonomic findings. It is a workflow recommendation, not a diagnosis or individual prognosis.": "Predlagani ukrep združuje prijavljene simptome, funkcionalni vpliv oziroma vpliv na delo ter relevantne ergonomske ugotovitve. Gre za priporočilo za nadaljnje ukrepanje, ne za diagnozo ali individualno prognozo.",
    "Region": "Predel",
    "Symptoms": "Simptomi",
    "Work impact": "Vpliv na delo",
    "Ergonomic exposure/findings": "Ergonomska izpostavljenost / ugotovitve",
    "Proposed action": "Predlagani ukrep",
    "affects work": "vpliva na delo",
    "no reported interference": "ni poročanega vpliva",
    "task/pace modified": "spremenjena naloga/tempo",
    "No musculoskeletal symptoms were reported.": "Mišično-skeletni simptomi niso bili navedeni.",
    "- **Digital eye strain / visual fatigue reported**": "- **Navedena je bila digitalna obremenitev oči / vidna utrujenost**",
    "*The ≥6 h/day sitting flag is an operational screening flag, not a validated causal threshold.": "*Oznaka ≥6 ur/dan sedenja je operativna presejalna oznaka in ne validiran vzročni prag.",

    # Exposure profile / action
    "computer/mouse >4 h": "računalnik/miška >4 h",
    "limited forearm support": "omejena podpora podlakti",
    "sustained arm elevation": "dolgotrajno dvignjena roka",
    "posture finding": "ugotovitev glede drže",
    "high repetition": "visoka ponavljajočnost",
    "hand force": "sila roke",
    "forearm rotation": "rotacija podlakti",
    "high sitting exposure*": "visoka izpostavljenost sedenju*",
    "long static bouts": "dolga statična obdobja",
    "chair-fit findings": "ugotovitve glede prilagoditve stola",
    "posture/movement finding": "ugotovitev glede drže/gibanja",
    "support/clearance finding": "ugotovitev glede podpore/prostora",
    "ROSA action level": "akcijska raven ROSA",
    "No specific ergonomic factor identified": "Ni ugotovljenega specifičnega ergonomskega dejavnika",
    "No specific": "Ni ugotovljeno",
    "Ergonomic intervention + follow-up; consider clinical/occupational-health review if persistent or worsening": "Ergonomski ukrep + ponovno spremljanje; ob vztrajanju ali poslabšanju razmisli o klinični oceni oziroma oceni medicine dela",
    "Ergonomic review + symptom monitoring": "Ergonomski pregled + spremljanje simptomov",
    "Monitor symptoms and reassess if they persist/worsen": "Spremljaj simptome in ponovno oceni stanje, če vztrajajo ali se poslabšajo",
    "Prevention / exposure management": "Preprečevanje / obvladovanje izpostavljenosti",
    "Maintain current conditions": "Ohrani trenutne ustrezne pogoje",

    # Health / anthropometry
    "Body-fit references": "Antropometrične referenčne vrednosti",
    "Popliteal height": "Višina podkolenske kotanje",
    "Seated elbow height": "Višina komolca sede",
    "Seated eye height": "Višina oči sede",
    "Physical activity and exercise are recorded as wellbeing/intervention context. They do not subtract points from a disease score.": "Telesna dejavnost in vadba se beležita kot kontekst dobrega počutja in ukrepov. Ne odštevata točk od nobene ocene bolezni.",

    # Work exposure / workstation
    "Choose options": "Izberi predele",
    "Work exposure": "Izpostavljenost pri delu",
    "Advanced upper-limb / shoulder exposure": "Napredna ocena izpostavljenosti zgornjega uda / rame",
    "Only flag these when the actual task exposure exists. They should not be inferred from ordinary computer use.": "Označi jih samo, kadar pri nalogi dejansko obstaja takšna izpostavljenost. Ne sklepaj o njih samo iz običajne uporabe računalnika.",
    "Measured values are compared with body-fit/design references. Differences are prompts for observation, not validated disease thresholds.": "Izmerjene vrednosti se primerjajo z antropometričnimi oziroma oblikovalskimi referencami. Odstopanja so izhodišče za opazovanje, ne validirani pragovi bolezni.",
    "Seat/body reference": "Referenca za višino sedeža",
    "Work-surface/elbow reference": "Referenca delovne površine/komolca",
    "body-fit reference": "antropometrična referenca",
    "Monitor v2 uses actual viewing distance + vertical position rather than a universal 'eye level − 5 cm' formula.": "V različici v2 se zaslon ocenjuje z dejansko razdaljo gledanja in navpičnim položajem, ne z univerzalno formulo »višina oči − 5 cm«.",
    "DSE environment": "Okolje za delo z zaslonom",
    "Lighting is adequate": "Osvetlitev je ustrezna",
    "Noise is acceptable for the task": "Hrup je sprejemljiv za nalogo",
    "Thermal comfort is acceptable": "Toplotno ugodje je sprejemljivo",
    "Software/interface supports the task without avoidable strain": "Programska oprema/vmesnik podpira nalogo brez nepotrebne obremenitve",
    "These fields support a broader EU display-screen assessment and are kept separate from musculoskeletal disease scoring.": "Ta polja podpirajo širšo evropsko oceno dela z zasloni in ostajajo ločena od ocenjevanja mišično-skeletnih bolezni.",

    # Chair / posture
    "Reference: EN 1335 / ISO 9241-5 design principles. Full conformity requires the official standard and its complete test method.": "Referenca: načela oblikovanja EN 1335 / ISO 9241-5. Popolna skladnost zahteva uradni standard in celotno preskusno metodo.",
    "Assessment completed": "Ocena zaključena",
    "Items confirmed": "Potrjena merila",
    "No compliance percentage or clinical risk band is generated.": "Ne izračuna se odstotek skladnosti ali klinična kategorija tveganja.",
    "Mark the section as completed before chair findings are included in the report.": "Pred vključitvijo ugotovitev o stolu v poročilo označi razdelek kot zaključen.",
    "EN 1335 Type A reference dimensions — audit note": "Referenčne mere EN 1335 tip A — opomba za pregled",
    "Displayed for reference only; the screen above is not a product-certification procedure.": "Prikazano samo kot referenca; zgornji pregled ni postopek certificiranja izdelka.",
    "Prolonged static posture was flagged. Postural variation should be increased.": "Ugotovljena je bila dolgotrajna statična drža. Povečati je treba spreminjanje položaja.",
    "Optional angle recording": "Neobvezno beleženje kota",
    "Observed elbow angle (°)": "Izmerjeni kot komolca (°)",
    "Mark the section as completed before posture findings are included in the report.": "Pred vključitvijo ugotovitev o drži v poročilo označi razdelek kot zaključen.",

    # ROSA
    "Visual ROSA worksheet & icons": "Vizualni obrazec ROSA in ikone",
    "Download ROSA worksheet PDF": "Prenesi obrazec ROSA v PDF",
    "The ROSA visual guide could not be loaded. The assessment below remains available.": "Vizualnega vodnika ROSA ni bilo mogoče naložiti. Spodnja ocena ostaja na voljo.",
    "ROSA media files are unavailable.": "Predstavnostne datoteke ROSA niso na voljo.",
    "Click the banner to open the worksheet, or use the PDF download button. The controls below follow the same scoring structure.": "Klikni pasico za odprtje obrazca ali uporabi gumb za prenos PDF. Spodnja polja sledijo isti strukturi točkovanja.",
    "### A · Chair": "### A · Stol",
    "#### A.1 · Chair height": "#### A.1 · Višina stola",
    "Select the picture/condition that best matches the worker": "Izberi sliko/stanje, ki najbolje ustreza zaposlenemu",
    "Knees at about 90° (+1)": "Kolena približno 90° (+1)",
    "Chair too low: knee angle <90° (+2)": "Stol je prenizek: kot kolena <90° (+2)",
    "Chair too high: knee angle >90° (+2)": "Stol je previsok: kot kolena >90° (+2)",
    "No foot contact with the floor (+3)": "Stopala nimajo stika s tlemi (+3)",
    "Insufficient space under the desk / cannot comfortably move the legs (+1)": "Premalo prostora pod mizo / nog ni mogoče udobno premikati (+1)",
    "Chair height is non-adjustable (+1)": "Višina stola ni nastavljiva (+1)",
    "#### A.2 · Seat pan depth": "#### A.2 · Globina sedeža",
    "Select seat-depth condition": "Izberi stanje, ki opisuje globino sedeža",
    "About 3 in / 7–8 cm between the back of the knee and seat edge (+1)": "Približno 7–8 cm med zadnjo stranjo kolena in robom sedeža (+1)",
    "Too long: less than ~7–8 cm of space (+2)": "Prevelika globina: manj kot ~7–8 cm prostora (+2)",
    "Too short: more than ~7–8 cm of space (+2)": "Premajhna globina: več kot ~7–8 cm prostora (+2)",
    "Seat depth is non-adjustable (+1)": "Globina sedeža ni nastavljiva (+1)",
    "#### A.3 · Armrests": "#### A.3 · Nasloni za roke",
    "Select armrest condition": "Izberi stanje naslonov za roke",
    "Elbows supported in line with the shoulders; shoulders relaxed (+1)": "Komolci so podprti ob telesu, ramena so sproščena (+1)",
    "Armrests too high or too low; shoulders shrugged or arms unsupported (+2)": "Nasloni za roke so previsoki ali prenizki; ramena so dvignjena ali roke niso podprte (+2)",
    "Armrest surface is hard/damaged (+1)": "Površina naslonov je trda ali poškodovana (+1)",
    "Armrests are too far apart (+1)": "Nasloni za roke so preveč narazen (+1)",
    "Armrests are non-adjustable (+1)": "Nasloni za roke niso nastavljivi (+1)",
    "#### A.4 · Back support": "#### A.4 · Opora za hrbet",
    "Select back-support condition": "Izberi stanje opore za hrbet",
    "Adequate lumbar support; backrest about 95–110° (+1)": "Ustrezna ledvena opora; naslon približno 95–110° (+1)",
    "No lumbar support OR lumbar support not positioned in the small of the back (+2)": "Ni ledvene opore ALI ni pravilno nameščena v ledvenem delu (+2)",
    "Backrest angled too far back (>110°) or too far forward (<95°) (+2)": "Naslon je preveč nazaj (>110°) ali preveč naprej (<95°) (+2)",
    "No back support / stool / worker leaning forward without support (+3)": "Brez opore za hrbet / stol brez naslona / zaposleni se nagiba naprej brez opore (+3)",
    "Work surface too high; shoulders shrugged (+1)": "Delovna površina je previsoka; ramena so dvignjena (+1)",
    "Backrest is non-adjustable (+1)": "Naslon ni nastavljiv (+1)",
    "Duration": "Trajanje",
    "### B · Monitor & phone": "### B · Zaslon in telefon",
    "#### B.1 · Monitor": "#### B.1 · Zaslon",
    "Select monitor-height condition": "Izberi stanje, ki najbolje opisuje višino zaslona",
    "Arm's-length distance (about 40–75 cm) and screen at eye level (+1)": "Razdalja približno dolžine roke (40–75 cm), zaslon v višini oči (+1)",
    "Monitor too low (below ~30° viewing angle) (+2)": "Zaslon je prenizek (pod približno 30° vidnega kota) (+2)",
    "Monitor too high, producing neck extension (+3)": "Zaslon je previsok in povzroča izteg vratu (+3)",
    "Monitor too far away (+1)": "Zaslon je predaleč (+1)",
    "Neck rotation >30° (+1)": "Rotacija vratu >30° (+1)",
    "Glare on screen (+1)": "Bleščanje / odsevi na zaslonu (+1)",
    "Documents used without a document holder (+1)": "Uporaba dokumentov brez držala (+1)",
    "#### B.2 · Phone": "#### B.2 · Telefon",
    "Baseline: headset or one-hand phone use with a neutral neck posture (+1). Add any conditions that apply.": "Osnovno stanje: slušalke ali uporaba telefona z eno roko ob nevtralnem položaju vratu (+1). Dodaj vse pogoje, ki veljajo.",
    "Phone is too far to reach (>30 cm) (+2)": "Telefon je predaleč (>30 cm) (+2)",
    "Phone held between neck and shoulder (+2)": "Telefon je stisnjen med vrat in ramo (+2)",
    "No hands-free option available (+1)": "Ni možnosti prostoročnega telefoniranja / slušalk (+1)",
    "### C · Mouse & keyboard": "### C · Miška in tipkovnica",
    "#### C.1 · Mouse": "#### C.1 · Miška",
    "Baseline: mouse in line with the shoulder (+1). Add any conditions that apply.": "Osnovno stanje: miška je v liniji z ramo (+1). Dodaj vse pogoje, ki veljajo.",
    "Reaching to use the mouse (+2)": "Za uporabo miške je potrebno seganje (+2)",
    "Mouse and keyboard are on different surfaces/heights (+2)": "Miška in tipkovnica sta na različnih površinah/višinah (+2)",
    "Pinch grip on mouse (+1)": "Ščipalni prijem miške (+1)",
    "Palmrest in front of the mouse (+1)": "Opora za dlan pred miško (+1)",
    "#### C.2 · Keyboard": "#### C.2 · Tipkovnica",
    "Baseline: wrists straight and shoulders relaxed (+1). Add any conditions that apply.": "Osnovno stanje: zapestja so nevtralna in ramena sproščena (+1). Dodaj vse pogoje, ki veljajo.",
    "Wrist extension / positive keyboard angle (>15° wrist extension) (+2)": "Izteg zapestja / pozitiven naklon tipkovnice (>15° iztega zapestja) (+2)",
    "Wrist deviation while typing (+1)": "Odklon zapestja med tipkanjem (+1)",
    "Keyboard too high; shoulders shrugged (+1)": "Tipkovnica je previsoko; ramena so dvignjena (+1)",
    "Reaching to overhead items (+1)": "Seganje po predmetih nad višino ramen (+1)",
    "Keyboard platform is non-adjustable (+1)": "Podlaga za tipkovnico ni nastavljiva (+1)",
    "ROSA results": "Rezultati ROSA",
    "Chair ROSA": "ROSA – stol",
    "Monitor & peripherals": "Zaslon in periferne naprave",
    "ROSA final": "Končni ROSA",
    "ROSA action level reached (≥5): further ergonomic investigation/intervention indicated.": "Dosežena je akcijska raven ROSA (≥5): priporočena sta nadaljnja ergonomska analiza in ukrepanje.",
    "ROSA below the validated action level of 5. This is not a clinical 'low disease risk' category.": "ROSA je pod validirano akcijsko ravnjo 5. To ni klinična kategorija »nizkega tveganja za bolezen«.",
    "Mark ROSA as completed before a score is included in the report.": "Pred vključitvijo rezultata v poročilo označi ROSA kot zaključeno.",

    # Evidence / summary
    "Findings from this assessment": "Ugotovitve te ocene",
    "No priority exposure finding was generated from the entered data.": "Iz vnesenih podatkov ni bila ugotovljena izpostavljenost visoke prioritete.",
    "Research evidence by body region": "Znanstveni dokazi po telesnih predelih",
    "Each section keeps evidence for the same body region together. Every study starts with a plain-language explanation; statistical details are optional.": "Dokazi za isti telesni predel so združeni. Vsaka študija se začne s preprosto razlago; statistične podrobnosti so neobvezne.",
    "No evidence cards are triggered until relevant exposure/symptom information is entered.": "Dokazi se ne prikažejo, dokler niso vneseni relevantni podatki o izpostavljenosti ali simptomih.",
    "Full v2 evidence library": "Celotna knjižnica znanstvenih dokazov v2",
    "The full library is also organised by body region. Research estimates are not combined into a single disease-risk score.": "Celotna knjižnica je urejena po telesnih predelih. Ocene iz raziskav se ne združujejo v eno samo oceno tveganja bolezni.",
    "This report summarises identified ergonomic exposures, reported symptoms, ROSA results and preventive actions. It does not calculate an individual probability of disease.": "Poročilo povzema ugotovljene ergonomske izpostavljenosti, prijavljene simptome, rezultate ROSA ter preventivne ukrepe. Ne izračunava individualne verjetnosti bolezni.",
    "ROSA reached the validated action level (≥5), so further ergonomic investigation and intervention are indicated.": "ROSA je dosegel validirano akcijsko raven (≥5), zato sta indicirana nadaljnja ergonomska analiza in ukrepanje.",
    "ROSA is below the action level of 5. This does not mean that all ergonomic issues or symptoms are absent.": "ROSA je pod akcijsko ravnjo 5. To ne pomeni, da ni drugih ergonomskih težav ali simptomov.",
    "Identified ergonomic factors": "Ugotovljeni ergonomski dejavniki",
    "Immediate priority": "Takojšnja prioriteta",
    "Needs attention": "Zahteva pozornost",
    "Additional context": "Dodatni kontekst",
    "No priority ergonomic exposure was identified from the entered information.": "Iz vnesenih podatkov ni bila ugotovljena ergonomska izpostavljenost visoke prioritete.",
    "Preventive and improvement measures": "Preventivni ukrepi in izboljšave",
    "Implement first": "Izvedi najprej",
    "Next actions": "Naslednji ukrepi",
    "Good practices to maintain": "Dobre prakse, ki jih je treba ohraniti",
    "Before vs after interventions": "Primerjava pred in po ukrepih",
    "The comparison evaluates change in ergonomic exposure indicators, symptoms and ROSA. It does not estimate a change in personal disease probability.": "Primerjava ocenjuje spremembe ergonomskih kazalnikov izpostavljenosti, simptomov in ROSA. Ne ocenjuje spremembe osebne verjetnosti bolezni.",
    "ROSA after": "ROSA po ukrepih",
    "High-priority issues after": "Težave visoke prioritete po ukrepih",
    "Attention issues after": "Težave, ki zahtevajo pozornost po ukrepih",
    "Interventions implemented": "Izvedeni ukrepi",
    "Change in symptoms": "Sprememba simptomov",
    "improved": "izboljšanje",
    "increased symptoms": "povečanje simptomov",
    "no change": "brez spremembe",
    "Digital eye strain": "Digitalna obremenitev oči",
    "High hand/wrist repetition": "Visoka ponavljajočnost gibov roke/zapestja",
    "Forceful hand/finger exertion": "Velika sila roke/prstov",
    "Forearm rotation exposure": "Izpostavljenost rotaciji podlakti",
    "Sustained arm elevation": "Dolgotrajno dvignjena roka",
    "Glare/reflections": "Bleščanje/odsevi",
    "Active breaks / postural changes": "Aktivni odmori / spremembe drže",
    "Keyboard/mouse close to the body": "Tipkovnica/miška blizu telesa",
    "Forearm support": "Podpora podlakti",
    "Observed improvements": "Zabeležene izboljšave",
    "No clear improvement was identified in the selected comparison indicators.": "Pri izbranih primerjalnih kazalnikih ni bilo ugotovljeno jasno izboljšanje.",
    "New issues identified": "Nove ugotovljene težave",
    "Issues still requiring attention": "Težave, ki še vedno zahtevajo pozornost",
    "A follow-up assessment is most useful when it is performed after the agreed measures have had enough time to be implemented and used in normal work.": "Ponovna ocena je najbolj uporabna, ko so dogovorjeni ukrepi dovolj dolgo uvedeni in uporabljeni pri običajnem delu.",
    "ErgoFit Intelligence v2 · Scientific architecture: evidence registry + separate exposure/symptom/intervention domains · Alpha build": "ErgoFit Intelligence v2 · Znanstvena arhitektura: register dokazov + ločena področja izpostavljenosti/simptomov/ukrepov · različica alpha",

    # Engine findings
    "Current/recent musculoskeletal symptoms": "Trenutni/nedavni mišično-skeletni simptomi",
    "Computer/mouse exposure >4 h/day": "Uporaba računalnika/miške >4 h/dan",
    "Prospective computer-worker evidence supports a small increase in broad arm/neck/shoulder complaints (CANS). This does not validate CTS prediction from computer hours.": "Prospektivni podatki pri uporabnikih računalnika kažejo majhno povečanje splošnih težav zgornjega uda, vratu in ramen (CANS). To ne omogoča napovedovanja sindroma karpalnega kanala iz števila ur uporabe računalnika.",
    "High occupational sitting exposure": "Visoka izpostavljenost sedenju pri delu",
    "≥6 h/day is used here as an operational exposure flag, not as a study-derived causal threshold. Sitting–pain associations are mainly cross-sectional.": "≥6 h/dan se uporablja kot operativna oznaka izpostavljenosti in ne kot vzročni prag iz raziskav. Povezave med sedenjem in bolečino večinoma izhajajo iz presečnih podatkov.",
    "Long uninterrupted sitting bouts": "Dolga neprekinjena obdobja sedenja",
    "Long static bouts reduce postural variation. The app does not treat any single break interval as a medical threshold.": "Dolga statična obdobja zmanjšujejo spreminjanje drže. Orodje nobenega posameznega intervala odmora ne obravnava kot medicinski prag.",
    "Limited active breaks / postural variation": "Omejeni aktivni odmori / omejeno spreminjanje drže",
    "Office-worker intervention evidence supports active breaks and postural change more consistently than passive rest or a fixed universal interval.": "Dokazi iz intervencijskih raziskav pri pisarniških zaposlenih dosledneje podpirajo aktivne odmore in spremembe drže kot pasivni počitek ali enoten univerzalni interval.",
    "High hand/wrist repetition": "Visoka ponavljajočnost gibov roke/zapestja",
    "This exposure has prospective evidence for clinically assessed CTS in occupational cohorts. Applicability depends on whether the task resembles the studied high-repetition work.": "Za takšno izpostavljenost obstajajo prospektivni dokazi o povezavi s klinično ocenjenim sindromom karpalnega kanala v delovnih kohortah. Uporabnost je odvisna od podobnosti naloge z raziskanim visoko ponavljajočim delom.",
    "Meaningful hand/finger force": "Pomembna sila roke/prstov",
    "Prospective occupational evidence links force intensity with clinically assessed CTS; typical office tasks often have much lower force.": "Prospektivni podatki iz delovnih okolij povezujejo intenzivnost sile s klinično ocenjenim sindromom karpalnega kanala; običajne pisarniške naloge pogosto zahtevajo precej manj sile.",
    "Substantial forearm rotation exposure": "Pomembna izpostavljenost rotaciji podlakti",
    "Prospective evidence supports an association with lateral epicondylitis when exposure is substantial.": "Prospektivni dokazi podpirajo povezavo z lateralnim epikondilitisom, kadar je izpostavljenost pomembna.",
    "Sustained arm elevation / shoulder load": "Dolgotrajno dvignjena roka / obremenitev rame",
    "Evidence is mainly from manual/mixed occupations and is indirect for standard office work; use only because actual exposure was reported.": "Dokazi izvirajo predvsem iz fizičnih ali mešanih poklicev in so za običajno pisarniško delo posredni; ugotovitev je uporabljena le, ker je bila dejanska izpostavljenost navedena.",
    "Seat height differs from body-fit reference": "Višina sedeža odstopa od antropometrične reference",
    "Work-surface height differs from elbow-height reference": "Višina delovne površine odstopa od reference višine komolca",
    "Monitor viewing distance outside reference range": "Razdalja gledanja zaslona je zunaj referenčnega območja",
    "Monitor vertical position needs review": "Navpični položaj zaslona je treba preveriti",
    "Use eye level, screen centre, viewing distance and corrective-lens needs together. v2 does not convert monitor height into a neck-disease coefficient.": "Skupaj upoštevaj višino oči, središče zaslona, razdaljo gledanja in potrebe po korekcijskih lečah. v2 višine zaslona ne pretvarja v koeficient tveganja za bolezen vratu.",
    "Keyboard/mouse positioned away from the body": "Tipkovnica/miška sta postavljeni predaleč od telesa",
    "Reaching can increase static shoulder/upper-limb demand; assess actual posture and task variation.": "Seganje lahko poveča statično obremenitev rame in zgornjega uda; oceni dejansko držo in raznolikost naloge.",
    "Limited forearm support": "Omejena podpora podlakti",
    "Where symptoms/exposure justify it, arm support combined with an alternative mouse has some office-RCT evidence for neck/shoulder outcomes.": "Kadar simptomi in izpostavljenost to upravičujejo, ima kombinacija podpore roke in alternativne miške nekaj dokazov iz randomiziranih pisarniških raziskav za izide vratu/ramen.",
    "Glare / reflections reported": "Navedeno bleščanje / moteči odsevi",
    "Visual-environment factors belong in a complete DSE assessment and should be corrected independently of musculoskeletal disease scoring.": "Dejavniki vidnega okolja sodijo v celovito oceno dela z zaslonom in jih je treba obravnavati neodvisno od ocenjevanja mišično-skeletnih bolezni.",
    "Digital eye strain / visual fatigue reported": "Navedena digitalna obremenitev oči / vidna utrujenost",
    "Treat this as a visual/DSE symptom finding. It is not combined with the musculoskeletal evidence profile or a disease score.": "Obravnavaj kot vidni simptom pri delu z zaslonom. Ne združuje se z mišično-skeletnim profilom dokazov ali oceno bolezni.",
    "lighting": "osvetlitev",
    "noise": "hrup",
    "thermal comfort": "toplotno ugodje",
    "software/interface ergonomics": "ergonomija programske opreme/vmesnika",
    "Work-environment factors need review": "Dejavnike delovnega okolja je treba pregledati",
    "Chair findings are engineering/fit findings. The number of failed items is not treated as a validated clinical-priority threshold, and chair replacement alone should not be presented as a validated treatment for back pain.": "Ugotovitve o stolu se nanašajo na prilagoditev in zasnovo. Število neizpolnjenih meril se ne uporablja kot validiran klinični prag prioritete, zamenjava stola sama po sebi pa se ne predstavlja kot dokazano zdravljenje bolečine v križu.",
    "These are posture-screening observations. v2 deliberately does not aggregate them into an overall posture percentage or disease-risk category.": "Gre za presejalna opažanja drže. v2 jih namenoma ne združuje v skupni odstotek drže ali kategorijo tveganja bolezni.",
    "The original ROSA validation supports score 5 as an action level for further ergonomic investigation/intervention.": "Prvotna validacija ROSA podpira rezultat 5 kot akcijsko raven za nadaljnjo ergonomsko analizo oziroma ukrepanje.",
    "Below the validated action level of 5. This is not interpreted as a clinical low-risk disease category.": "Rezultat je pod validirano akcijsko ravnjo 5. Ne razlaga se kot klinična kategorija nizkega tveganja bolezni.",
    "BMI can be associated with some musculoskeletal/neuropathic outcomes, but it is not an ergonomic exposure and is not converted into an ErgoFit disease score.": "ITM je lahko povezan z nekaterimi mišično-skeletnimi ali nevropatskimi izidi, vendar ni ergonomska izpostavljenost in se ne pretvarja v oceno bolezni ErgoFit.",
    "Sleep concern": "Težava s spanjem",
    "Sleep problems and chronic musculoskeletal pain are prospectively associated and bidirectional. v2 treats sleep as context, not as a numeric protective/risk credit.": "Težave s spanjem in kronična mišično-skeletna bolečina so prospektivno povezane in odnos je dvosmeren. v2 spanec obravnava kot zdravstveni kontekst, ne kot številčno zaščitno ali obremenilno točko.",
    "Psychosocial work factors flagged": "Ugotovljeni psihosocialni dejavniki dela",
    "Psychosocial and organisational factors can contribute to symptom development/persistence. They are kept separate from workstation geometry and disease prediction.": "Psihosocialni in organizacijski dejavniki lahko prispevajo k nastanku ali vztrajanju simptomov. Obravnavajo se ločeno od geometrije delovnega mesta in napovedovanja bolezni.",

    # Recommendations
    "Follow up symptoms with functional/work impact": "Ponovno spremljaj simptome s funkcionalnim vplivom oziroma vplivom na delo",
    "Address relevant ergonomic exposures, document symptom/function change at reassessment, and use the appropriate occupational-health or clinical pathway if symptoms persist, worsen, or materially limit work.": "Obravnavaj relevantne ergonomske izpostavljenosti, ob ponovni oceni dokumentiraj spremembo simptomov in funkcije ter uporabi ustrezno pot medicine dela ali klinične obravnave, če simptomi vztrajajo, se slabšajo ali pomembno omejujejo delo.",
    "This is a functional follow-up rule, not a disease-probability prediction. Pain intensity alone is not used as a validated prognostic cutoff.": "Gre za pravilo funkcionalnega spremljanja, ne za napoved verjetnosti bolezni. Intenzivnost bolečine sama po sebi se ne uporablja kot validiran prognostični prag.",
    "Act on the ROSA drivers": "Ukrepaj glede dejavnikov, ki zvišujejo ROSA",
    "Review the specific chair, monitor, phone, mouse and keyboard ROSA sub-items that generated the score and correct the highest-exposure items first.": "Preglej posamezne postavke ROSA za stol, zaslon, telefon, miško in tipkovnico, ki so oblikovale rezultat, ter najprej popravi postavke z največjo izpostavljenostjo.",
    "ROSA ≥5 reaches the validated action level for further ergonomic investigation/intervention.": "ROSA ≥5 doseže validirano akcijsko raven za nadaljnjo ergonomsko analizo oziroma ukrepanje.",
    "Correct workstation fit before adding accessories": "Izboljšaj prilagoditev delovnega mesta",
    "Adjust seat height, work-surface relationship and monitor placement using direct body measurements and observed posture. Re-check after adjustment.": "Prilagodi višino sedeža, razmerje do delovne površine in položaj zaslona na podlagi neposrednih telesnih mer ter opazovane drže. Po prilagoditvi ponovno preveri.",
    "Workstation fit is an engineering exposure-control step. The app does not claim a specific disease-risk reduction from a centimetre change.": "Prilagoditev delovnega mesta je tehnični ukrep obvladovanja izpostavljenosti. Orodje ne trdi, da sprememba nekaj centimetrov pomeni določeno zmanjšanje tveganja bolezni.",
    "Review the visual workstation": "Preglej vidno delovno okolje",
    "Reduce glare/reflections, confirm viewing distance and display position, and follow the organisation's eyesight/occupational-health pathway if visual symptoms persist.": "Zmanjšaj bleščanje in odseve, preveri razdaljo gledanja in položaj zaslona ter ob vztrajanju vidnih simptomov sledi postopku organizacije za pregled vida oziroma medicino dela.",
    "A complete display-screen assessment includes visual symptoms and the visual environment, not only musculoskeletal geometry.": "Celovita ocena dela z zaslonom vključuje vidne simptome in vidno okolje, ne le mišično-skeletne geometrije.",
    "Correct flagged DSE environment factors": "Odpravi ugotovljene dejavnike okolja pri delu z zaslonom",
    "Address lighting, noise, thermal comfort and/or software-interface issues that were marked unsuitable for the task.": "Obravnavaj težave z osvetlitvijo, hrupom, toplotnim ugodjem in/ali programsko opremo oziroma vmesnikom, ki so bile označene kot neustrezne za nalogo.",
    "The display-screen workstation includes the immediate work environment and software, so these should be controlled as separate ergonomic domains.": "Delovno mesto z zaslonom vključuje neposredno delovno okolje in programsko opremo, zato ju je treba obravnavati kot ločeni ergonomski področji.",
    "Increase movement and postural variation": "Povečaj gibanje in spreminjanje drže",
    "Use short active breaks and regular position changes that fit the workflow. Avoid presenting one fixed interval as a universal medical threshold.": "Uporabljaj kratke aktivne odmore in redne spremembe položaja, ki ustrezajo delovnemu procesu. Enotnega intervala ne predstavljaj kot univerzalni medicinski prag.",
    "Office intervention evidence is more supportive of active breaks/postural change than of a single prescribed break schedule.": "Dokazi iz pisarniških intervencij bolj podpirajo aktivne odmore in spremembe drže kot enoten predpisan urnik odmorov.",
    "Consider targeted neck/shoulder exercise": "Razmisli o ciljani vadbi za vrat/ramena",
    "Where clinically appropriate, use progressive neck/shoulder/scapular strengthening or workplace micro-exercise rather than treating exercise as a numeric 'protective credit'.": "Kjer je klinično primerno, uporabi progresivno krepitev vratu, ramen in lopatic ali kratke vaje na delovnem mestu; vadbe ne obravnavaj kot številčno »zaščitno točko«.",
    "Recent RCT meta-analysis in sedentary workers supports improvement in combined neck/shoulder pain and neck disability, with moderate certainty for selected outcomes.": "Novejša meta-analiza randomiziranih raziskav pri sedečih zaposlenih podpira izboljšanje kombinirane bolečine v vratu/ramenih in funkcionalne prizadetosti vratu, z zmerno gotovostjo za izbrane izide.",
    "Use a multicomponent low-back strategy": "Uporabi večkomponentni pristop za križ",
    "Combine workstation correction with appropriate physical activity/exercise and movement variation; do not rely on chair replacement alone.": "Združi prilagoditev delovnega mesta z ustrezno telesno dejavnostjo/vadbo in spreminjanjem položaja; ne zanašaj se samo na zamenjavo stola.",
    "Office-worker network meta-analysis suggests only modest/uncertain benefits across many interventions, with some support for physical activity plus ergonomics.": "Mrežna meta-analiza pri pisarniških zaposlenih kaže večinoma majhne ali negotove koristi številnih ukrepov, z nekaj podpore kombinaciji telesne dejavnosti in ergonomije.",
    "Review mouse reach and forearm support": "Preglej doseg miške in podporo podlakti",
    "Keep the mouse close, minimise unnecessary reach, and consider a suitable forearm-support/alternative-mouse combination when symptoms and task demands justify it.": "Miško drži blizu telesa, zmanjša nepotrebno seganje in, kadar to upravičujejo simptomi ter zahteve naloge, razmisli o primerni kombinaciji podpore podlakti in alternativne miške.",
    "Cochrane office-worker evidence supports a specific arm-support + alternative-mouse combination for some neck/shoulder outcomes; evidence does not support generic equipment claims.": "Cochrane dokazi pri pisarniških zaposlenih podpirajo specifično kombinacijo podpore roke in alternativne miške za nekatere izide vratu/ramen; dokazi ne podpirajo splošnih trditev za vsak ergonomski pripomoček.",
    "Quantify upper-limb mechanical exposure": "Kvantificiraj mehansko izpostavljenost zgornjega uda",
    "If the job truly involves high repetition or force, use a task-appropriate method such as ACGIH HAL or Strain Index and redesign the task rather than using computer-hours as a proxy.": "Če delo dejansko vključuje visoko ponavljajočnost ali silo, uporabi primerno metodo, kot sta ACGIH HAL ali Strain Index, in preoblikuj nalogo namesto uporabe ur računalnika kot nadomestnega kazalnika.",
    "Prospective CTS evidence is strongest for repetition, force, HAL and Strain Index.": "Najmočnejši prospektivni dokazi za sindrom karpalnega kanala se nanašajo na ponavljanje, silo, HAL in Strain Index.",
    "Reduce sustained forearm rotation": "Zmanjšaj dolgotrajno rotacijo podlakti",
    "Modify task orientation, tool/device position or work sequence so the forearm can remain closer to neutral and rotate less often/less intensely.": "Spremeni usmeritev naloge, položaj orodja/naprave ali zaporedje dela, da podlaket ostane bližje nevtralnemu položaju in se manj pogosto oziroma manj intenzivno rotira.",
    "Prospective evidence supports forearm rotation and higher Strain Index as lateral-epicondylitis exposures in relevant occupational tasks.": "Prospektivni dokazi podpirajo rotacijo podlakti in višji Strain Index kot izpostavljenosti, povezane z lateralnim epikondilitisom pri ustreznih delovnih nalogah.",
    "Reduce sustained arm elevation": "Zmanjšaj dolgotrajno dvigovanje roke",
    "Bring frequently used items into a lower, closer reach zone and reduce sustained shoulder elevation/loading.": "Pogosto uporabljene predmete premakni v nižje in bližje območje dosega ter zmanjšaj dolgotrajno dvigovanje oziroma obremenitev rame.",
    "Evidence for specific shoulder disorders comes mainly from manual/mixed occupations, so intervention is justified by the actual exposure, not by an office-worker disease score.": "Dokazi za specifične motnje rame izvirajo predvsem iz fizičnih oziroma mešanih poklicev, zato je ukrep upravičen zaradi dejanske izpostavljenosti in ne zaradi ocene bolezni pri pisarniškem zaposlenem.",
    "Optimise chair fit and adjustability": "Optimiziraj prilagoditev in nastavljivost stola",
    "Correct the failed fit/adjustability items and trial the chair during real work. Replace the chair only when fit/adjustment cannot be achieved.": "Odpravi neustrezne elemente prilagoditve/nastavljivosti in stol preizkusi pri dejanskem delu. Zamenjaj ga le, če ustrezne prilagoditve ni mogoče doseči.",
    "Chair-specific intervention evidence for pain prevention is very low/low and conflicting; fit remains a valid engineering objective.": "Dokazi za ukrepe, usmerjene samo v stol, pri preprečevanju bolečine so zelo nizke oziroma nizke gotovosti in nasprotujoči; ustrezna prilagoditev stola ostaja veljaven ergonomski cilj.",
    "Treat sleep as a health-context issue": "Spanec obravnavaj kot zdravstveni kontekst",
    "If sleep problems are persistent or significant, encourage appropriate sleep-health assessment/support. Do not subtract or add disease-risk points based on sleep duration alone.": "Če so težave s spanjem vztrajne ali pomembne, spodbudi ustrezno oceno oziroma podporo za zdravje spanja. Ne dodajaj ali odštevaj točk tveganja bolezni samo na podlagi trajanja spanja.",
    "Prospective evidence shows a bidirectional association between sleep problems and chronic musculoskeletal pain, but it is not office-specific and does not validate a numeric ErgoFit coefficient.": "Prospektivni dokazi kažejo dvosmerno povezavo med težavami s spanjem in kronično mišično-skeletno bolečino, vendar niso specifični za pisarniško delo in ne validirajo številčnega koeficienta ErgoFit.",
    "Maintain a well-fitted, variable workstation routine": "Ohrani dobro prilagojeno delovno mesto in raznoliko držo",
    "Continue using the workstation with regular position changes and re-assess if symptoms or task demands change.": "Delovno mesto uporabljaj z rednim spreminjanjem položaja in ponovno oceni stanje, če se simptomi ali zahteve naloge spremenijo.",
    "No priority ergonomic exposure was identified in this screen.": "Pri tej oceni ni bila ugotovljena ergonomska izpostavljenost visoke prioritete.",
}


def translate(lang: str, en: str, el: str) -> str:
    """Return English, Greek or Slovenian wording. Slovenian falls back to English."""
    if lang == "en":
        return en
    if lang == "el":
        return el
    if lang != "sl":
        return en

    if en in SL_TEXT:
        return SL_TEXT[en]

    # Dynamic strings generated by the assessment engine.
    if en.startswith("Symptom: "):
        return "Simptom: " + en[len("Symptom: "):]
    if en.startswith("ROSA action level reached ("):
        return en.replace("ROSA action level reached", "Dosežena akcijska raven ROSA", 1)
    if en.startswith("ROSA below action level ("):
        return en.replace("ROSA below action level", "ROSA pod akcijsko ravnjo", 1)
    if re.match(r"^\d+ chair fit/adjustability issue", en):
        n = en.split(" ", 1)[0]
        return f"{n} težav s prilagoditvijo/nastavljivostjo stola"
    if re.match(r"^\d+ posture criterion finding", en):
        n = en.split(" ", 1)[0]
        return f"{n} ugotovitev glede meril drže"
    if en.startswith("BMI category:"):
        return en.replace("BMI category:", "Kategorija ITM:", 1)
    if en.startswith("Measured ") and " vs reference " in en:
        return en.replace("Measured ", "Izmerjeno ", 1).replace(" vs reference ", " v primerjavi z referenco ", 1)
    if en.startswith("Flagged: "):
        return en.replace("Flagged: ", "Ugotovljeno: ", 1).replace(
            "These belong in a complete display-screen assessment and are not converted into MSD probability points.",
            "Ti dejavniki sodijo v celovito oceno dela z zaslonom in se ne pretvarjajo v točke verjetnosti mišično-skeletne bolezni.",
        )
    if en.startswith("Intensity "):
        return (
            en.replace("Intensity ", "Intenzivnost ", 1)
              .replace("; duration ", "; trajanje ")
              .replace("; frequency ", "; pogostost ")
              .replace("; work interference: ", "; vpliv na delo: ")
              .replace("; work absence (last 4 weeks): ", "; odsotnost z dela (zadnji 4 tedni): ")
              .replace(" day(s).", " dni.")
              .replace("No single pain-intensity cutoff is used as a validated prognostic threshold.",
                       "Noben posamezen prag intenzivnosti bolečine se ne uporablja kot validiran prognostični prag.")
        )

    return en
